apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: loadtest

# Example configuration for the webserver
# at https://github.com/monopole/hello
labels:
  - includeSelectors: false
    pairs:
      app: loadtest

resources:
- configmap.yaml
- namespace.yaml
- publisher.yaml
- rbac.yaml
- service.yaml
- subscriber.yaml
- subscriptions.yaml
