name: "Launch Metadata Creation Tool for REUSE"
on:
  workflow_dispatch: ~

jobs:
  create_metadata_proposal:
    runs-on: ubuntu-latest
    name: "Metadata Creation Tool"
    steps:
      - uses: SAP/metadata-creation-tool-for-reuse@main
        with:
          repository_url: "${{ github.server_url }}/${{ github.repository }}"
          access_token: "${{ secrets.GITHUB_TOKEN }}"
          copyright_owner: "Korbinian Stoemmer"
          upstream_contact: "Korbinian Stoemmer <korbinian.stoemmer@sap.com>"
